'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'ko' | 'vi' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  ko: {
    // Auth
    'login': '로그인',
    'signup': '회원가입',
    'logout': '로그아웃',
    'email': '이메일',
    'username': '아이디',
    'password': '비밀번호',
    'confirmPassword': '비밀번호 확인',
    'name': '이름',
    'grade': '학년',
    'loginButton': '로그인',
    'signupButton': '회원가입',
    'loggingIn': '로그인 중...',
    'signingUp': '가입 중...',
    'alreadyHaveAccount': '이미 계정이 있으신가요?',
    'noAccount': '계정이 없으신가요?',
    'forgotPassword': '비밀번호를 잊으셨나요?',
    'passwordMismatch': '비밀번호가 일치하지 않습니다',
    'welcomeToKGSCP': 'Korea Global School Community Platform에 오신 것을 환영합니다',
    'joinCommunity': 'KGSCP 커뮤니티에 참여하세요',
    'loginFailed': '로그인 실패',
    'signupFailed': '회원가입 실패',
    'profileCreateFailed': '프로필 생성 실패',
    'signupSuccess': '회원가입이 완료되었습니다',
    'signupCheckEmail': '가입 확인 이메일을 확인해주세요 (설정에 따라 생략될 수 있어요).',
    'selectGrade': '학년을 선택하세요',
    'gradeNumber': '학년',
    // Navigation
    'home': '홈',
    'boards': '게시판',
    'directory': '학생 목록',
    'myInfo': '내 정보',
    'messages': '쪽지',
    'settings': '설정',
    'admin': '관리자',
    // Messages
    'sendAnonymousMessages': '익명으로 쪽지를 주고받으세요',
    'sendMessage': '메시지 보내기',
    'sendAnonymously': '익명으로 메시지를 전송합니다',
    'searchStudent': '학생 검색',
    'receiver': '수신자',
    'noStudents': '학생이 없습니다',
    'selected': '명 선택됨',
    'type': '타입',
    'selectType': '타입 선택',
    'projectProposal': '과제 제안',
    'mentorMentee': '멘토 멘티',
    'schoolContest': '교내 대회',
    'club': '동아리',
    'otherQuestion': '기타 질문',
    'content': '내용',
    'enterMessageContent': '메시지 내용을 입력하세요...',
    'send': '전송',
    'sentMessages': '보낸 쪽지',
    'receivedMessages': '받은 쪽지',
    'onHold': '보류중',
    'chatRooms': '대화방',
    'to': '받는사람',
    'from': '보낸사람',
    'anonymous': '익명',
    'accepted': '수락됨',
    'rejected': '거절됨',
    'pending': '대기중',
    'accept': '수락',
    'reject': '거절',
    'hold': '보류',
    'noSentMessages': '보낸 쪽지가 없습니다',
    'noReceivedMessages': '받은 쪽지가 없습니다',
    'noPendingMessages': '보류중인 쪽지가 없습니다',
    'chatRoomList': '대화방 목록',
    'noChatRooms': '대화방이 없습니다',
    'enterMessage': '메시지 입력...',
    'selectChatRoom': '대화방을 선택하세요',
    'fillAllFields': '모든 필드를 입력해주세요',
    'messageSent': '쪽지가 전송되었습니다',
    'messageAccepted': '쪽지를 수락했습니다. 대화방이 생성되었습니다.',
    'confirmReject': '이 쪽지를 거절하시겠습니까?',
    'messageRejected': '쪽지가 거절되었습니다',
    'messagePending': '쪽지를 보류했습니다',
    // Directory
    'studentList': '학생 목록',
    'checkByGrade': '학년별로 학생들을 확인하세요',
    'searchByName': '이름으로 검색...',
    'all': '전체',
    'sendDirectMessage': '쪽지 보내기',
    'totalStudents': '총 {count}명의 학생',
    // Settings
    'manageSettings': '계정 설정을 관리하세요',
    'interests': '관심목록',
    'addInterests': '관심 있는 주제나 활동을 추가하세요',
    'addInterestPlaceholder': '관심사 추가 (예: 농구, 수학)',
    'add': '추가',
    'addInterestsPrompt': '관심사를 추가해보세요',
    'changePassword': '비밀번호 변경',
    'setNewPassword': '새로운 비밀번호를 설정하세요',
    'currentPassword': '현재 비밀번호',
    'newPassword': '새 비밀번호',
    'confirmNewPassword': '새 비밀번호 확인',
    'dangerZone': '위험 영역',
    'deleteAccountWarning': '계정 삭제는 되돌릴 수 없습니다',
    'deleteAccount': '회원 탈퇴',
    'confirmDelete': '정말 탈퇴하시겠습니까?',
    'deleteDescription': '이 작업은 되돌릴 수 없습니다. 모든 데이터가 영구적으로 삭제됩니다.',
    'cancel': '취소',
    // Home page translations
    'welcomeUser': '환영합니다, {name}님',
    'checkLatestPosts': 'KGSCP 학생 커뮤니티에서 최신 게시글을 확인하세요',
    'noPosts': '아직 게시글이 없습니다',
    'justNow': '방금 전',
    'hoursAgo': '{hours}시간 전',
    'daysAgo': '{days}일 전',
    'loading': '로딩 중...',
    // Boards page translations
    'boardTitle': '게시판',
    'shareStories': '학교 소식과 이야기를 나눠보세요',
    'category': '카테고리',
    'searchTitle': '제목 검색',
    'search': '검색...',
    'categoryAll': '전체',
    'categoryFree': '자유게시판',
    'categoryClub': '동아리',
    'categoryAssignment': '학교 과제',
    'categorySubject': '교과목',
    'categoryContest': '교내 대회',
    'categoryMentor': '멘토 멘티',
    'categoryOther': '기타',
    'newPost': '새 게시글',
    'selectCategory': '카테고리 선택',
    'title': '제목',
    'enterTitle': '제목을 입력하세요',
    'enterContent': '내용을 입력하세요',
    'fileUpload': '파일 업로드',
    'chooseFile': '파일 선택',
    'postAsAnonymous': '익명으로 게시',
    'submit': '게시하기',
    'backToList': '목록으로',
    'delete': '삭제',
    'like': '좋아요',
    'dislike': '싫어요',
    'comment': '댓글',
    'comments': '댓글',
    'writeComment': '댓글을 작성하세요...',
    'postComment': '댓글 입력',
    'reply': '답글',
    'firstComment': '첫 댓글을 작성해보세요',
    'replyingTo': '답글 작성 중...',
    'confirmDeletePost': '정말로 이 게시글을 삭제하시겠습니까?',
    'confirmDeleteComment': '정말로 이 댓글을 삭제하시겠습니까?',
    // Profile page translations
    'profileUpdated': '프로필이 업데이트되었습니다',
    'manageProfile': '내 프로필 정보를 관리하세요',
    'edit': '수정',
    'editProfile': '프로필 수정',
    'basicInfo': '기본 정보',
    'class': '반',
    'classNumber': '반 번호',
    'classPlaceholder': '예: 1반',
    'academicInfo': '학업 정보',
    'mbtiPlaceholder': '예: ENFP',
    'toeflPlaceholder': '예: 110',
    'satPlaceholder': '예: 1450',
    'apPlaceholder': '예: Calculus BC (5)',
    'otherScores': '기타 외부 성적',
    'otherScoresPlaceholder': '예: IELTS 8.0',
    'gpa': '내신',
    'gpaPlaceholder': '예: 4.0',
    'bestSubject': '가장 자신있는 과목',
    'bestSubjectPlaceholder': '예: 수학',
    'bio': '하고싶은말',
    'bioPlaceholder': '자신을 소개해주세요...',
    'save': '저장하기',
    'characterLimit': '{current}/{max}',
    'mbti': 'MBTI',
    'toefl': 'TOEFL',
    'sat': 'SAT',
    'ap': 'AP',
  },
  vi: {
    // Auth
    'login': 'Đăng nhập',
    'signup': 'Đăng ký',
    'logout': 'Đăng xuất',
    'email': 'Email',
    'username': 'Tên đăng nhập',
    'password': 'Mật khẩu',
    'confirmPassword': 'Xác nhận mật khẩu',
    'name': 'Tên',
    'grade': 'Lớp',
    'loginButton': 'Đăng nhập',
    'signupButton': 'Đăng ký',
    'loggingIn': 'Đang đăng nhập...',
    'signingUp': 'Đang đăng ký...',
    'alreadyHaveAccount': 'Bạn đã có tài khoản?',
    'noAccount': 'Bạn chưa có tài khoản?',
    'forgotPassword': 'Quên mật khẩu?',
    'passwordMismatch': 'Mật khẩu không khớp',
    'welcomeToKGSCP': 'Chào mừng đến với Korea Global School Community Platform',
    'joinCommunity': 'Tham gia cộng đồng KGSCP',
    'loginFailed': 'Đăng nhập thất bại',
    'signupFailed': 'Đăng ký thất bại',
    'profileCreateFailed': 'Tạo hồ sơ thất bại',
    'signupSuccess': 'Đăng ký thành công',
    'signupCheckEmail': 'Vui lòng kiểm tra email để xác nhận (có thể bị tắt trong cài đặt).',
    'selectGrade': 'Chọn lớp',
    'gradeNumber': 'Lớp',
    // Navigation
    'home': 'Trang chủ',
    'boards': 'Bảng tin',
    'directory': 'Danh sách học sinh',
    'myInfo': 'Thông tin',
    'messages': 'Tin nhắn',
    'settings': 'Cài đặt',
    'admin': 'Quản trị',
    // Messages
    'sendAnonymousMessages': 'Gửi và nhận tin nhắn ẩn danh',
    'sendMessage': 'Gửi tin nhắn',
    'sendAnonymously': 'Gửi tin nhắn ẩn danh',
    'searchStudent': 'Tìm học sinh',
    'receiver': 'Người nhận',
    'noStudents': 'Không có học sinh',
    'selected': ' đã chọn',
    'type': 'Loại',
    'selectType': 'Chọn loại',
    'projectProposal': 'Đề xuất dự án',
    'mentorMentee': 'Cố vấn',
    'schoolContest': 'Cuộc thi trường',
    'club': 'Câu lạc bộ',
    'otherQuestion': 'Câu hỏi khác',
    'content': 'Nội dung',
    'enterMessageContent': 'Nhập nội dung tin nhắn...',
    'send': 'Gửi',
    'sentMessages': 'Tin đã gửi',
    'receivedMessages': 'Tin đã nhận',
    'onHold': 'Đang chờ',
    'chatRooms': 'Phòng chat',
    'to': 'Đến',
    'from': 'Từ',
    'anonymous': 'Ẩn danh',
    'accepted': 'Đã chấp nhận',
    'rejected': 'Đã từ chối',
    'pending': 'Đang chờ',
    'accept': 'Chấp nhận',
    'reject': 'Từ chối',
    'hold': 'Giữ lại',
    'noSentMessages': 'Không có tin đã gửi',
    'noReceivedMessages': 'Không có tin đã nhận',
    'noPendingMessages': 'Không có tin đang chờ',
    'chatRoomList': 'Danh sách phòng chat',
    'noChatRooms': 'Không có phòng chat',
    'enterMessage': 'Nhập tin nhắn...',
    'selectChatRoom': 'Chọn phòng chat',
    'fillAllFields': 'Vui lòng điền tất cả các trường',
    'messageSent': 'Tin nhắn đã được gửi',
    'messageAccepted': 'Đã chấp nhận tin nhắn. Phòng chat đã được tạo.',
    'confirmReject': 'Bạn có chắc muốn từ chối tin nhắn này?',
    'messageRejected': 'Tin nhắn đã bị từ chối',
    'messagePending': 'Tin nhắn đã được giữ lại',
    // Directory
    'studentList': 'Danh sách học sinh',
    'checkByGrade': 'Kiểm tra học sinh theo lớp',
    'searchByName': 'Tìm theo tên...',
    'all': 'Tất cả',
    'sendDirectMessage': 'Gửi tin nhắn',
    'totalStudents': 'Tổng {count} học sinh',
    // Settings
    'manageSettings': 'Quản lý cài đặt tài khoản',
    'interests': 'Sở thích',
    'addInterests': 'Thêm chủ đề hoặc hoạt động quan tâm',
    'addInterestPlaceholder': 'Thêm sở thích (VD: bóng rổ, toán)',
    'add': 'Thêm',
    'addInterestsPrompt': 'Hãy thêm sở thích của bạn',
    'changePassword': 'Đổi mật khẩu',
    'setNewPassword': 'Đặt mật khẩu mới',
    'currentPassword': 'Mật khẩu hiện tại',
    'newPassword': 'Mật khẩu mới',
    'confirmNewPassword': 'Xác nhận mật khẩu mới',
    'dangerZone': 'Vùng nguy hiểm',
    'deleteAccountWarning': 'Xóa tài khoản không thể hoàn tác',
    'deleteAccount': 'Xóa tài khoản',
    'confirmDelete': 'Bạn có chắc muốn xóa tài khoản?',
    'deleteDescription': 'Hành động này không thể hoàn tác. Tất cả dữ liệu sẽ bị xóa vĩnh viễn.',
    'cancel': 'Hủy',
    // Home page translations
    'welcomeUser': 'Chào mừng, {name}',
    'checkLatestPosts': 'Kiểm tra bài đăng mới nhất từ cộng đồng học sinh KGSCP',
    'noPosts': 'Chưa có bài đăng',
    'justNow': 'Vừa xong',
    'hoursAgo': '{hours} giờ trước',
    'daysAgo': '{days} ngày trước',
    'loading': 'Đang tải...',
    // Boards page translations
    'boardTitle': 'Bảng tin',
    'shareStories': 'Chia sẻ tin tức và câu chuyện trường học',
    'category': 'Danh mục',
    'searchTitle': 'Tìm tiêu đề',
    'search': 'Tìm kiếm...',
    'categoryAll': 'Tất cả',
    'categoryFree': 'Bảng tự do',
    'categoryClub': 'Câu lạc bộ',
    'categoryAssignment': 'Bài tập trường',
    'categorySubject': 'Môn học',
    'categoryContest': 'Cuộc thi trường',
    'categoryMentor': 'Cố vấn',
    'categoryOther': 'Khác',
    'newPost': 'Bài đăng mới',
    'selectCategory': 'Chọn danh mục',
    'title': 'Tiêu đề',
    'enterTitle': 'Nhập tiêu đề',
    'enterContent': 'Nhập nội dung',
    'fileUpload': 'Tải tệp lên',
    'chooseFile': 'Chọn tệp',
    'postAsAnonymous': 'Đăng ẩn danh',
    'submit': 'Đăng bài',
    'backToList': 'Về danh sách',
    'delete': 'Xóa',
    'like': 'Thích',
    'dislike': 'Không thích',
    'comment': 'Bình luận',
    'comments': 'Bình luận',
    'writeComment': 'Viết bình luận...',
    'postComment': 'Đăng bình luận',
    'reply': 'Trả lời',
    'firstComment': 'Hãy viết bình luận đầu tiên',
    'replyingTo': 'Đang trả lời...',
    'confirmDeletePost': 'Bạn có chắc muốn xóa bài đăng này?',
    'confirmDeleteComment': 'Bạn có chắc muốn xóa bình luận này?',
    // Profile page translations
    'profileUpdated': 'Hồ sơ đã được cập nhật',
    'manageProfile': 'Quản lý thông tin hồ sơ của bạn',
    'edit': 'Chỉnh sửa',
    'editProfile': 'Chỉnh sửa hồ sơ',
    'basicInfo': 'Thông tin cơ bản',
    'class': 'Lớp',
    'classNumber': 'Số lớp',
    'classPlaceholder': 'VD: Lớp 1',
    'academicInfo': 'Thông tin học tập',
    'mbtiPlaceholder': 'VD: ENFP',
    'toeflPlaceholder': 'VD: 110',
    'satPlaceholder': 'VD: 1450',
    'apPlaceholder': 'VD: Calculus BC (5)',
    'otherScores': 'Điểm số khác',
    'otherScoresPlaceholder': 'VD: IELTS 8.0',
    'gpa': 'GPA',
    'gpaPlaceholder': 'VD: 4.0',
    'bestSubject': 'Môn học giỏi nhất',
    'bestSubjectPlaceholder': 'VD: Toán',
    'bio': 'Giới thiệu',
    'bioPlaceholder': 'Giới thiệu về bản thân...',
    'save': 'Lưu',
    'characterLimit': '{current}/{max}',
    'mbti': 'MBTI',
    'toefl': 'TOEFL',
    'sat': 'SAT',
    'ap': 'AP',
  },
  en: {
    // Auth
    'login': 'Login',
    'signup': 'Sign Up',
    'logout': 'Logout',
    'email': 'Email',
    'username': 'Username',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'name': 'Name',
    'grade': 'Grade',
    'loginButton': 'Login',
    'signupButton': 'Sign Up',
    'loggingIn': 'Logging in...',
    'signingUp': 'Signing up...',
    'alreadyHaveAccount': 'Already have an account?',
    'noAccount': "Don't have an account?",
    'forgotPassword': 'Forgot password?',
    'passwordMismatch': 'Passwords do not match',
    'welcomeToKGSCP': 'Welcome to Korea Global School Community Platform',
    'joinCommunity': 'Join the KGSCP community',
    'loginFailed': 'Login failed',
    'signupFailed': 'Sign up failed',
    'profileCreateFailed': 'Profile creation failed',
    'signupSuccess': 'Sign up completed',
    'signupCheckEmail': 'Please check your email to confirm (may be disabled in settings).',
    'selectGrade': 'Select grade',
    'gradeNumber': 'Grade',
    // Navigation
    'home': 'Home',
    'boards': 'Boards',
    'directory': 'Student List',
    'myInfo': 'My Info',
    'messages': 'Messages',
    'settings': 'Settings',
    'admin': 'Admin',
    // Messages
    'sendAnonymousMessages': 'Send and receive anonymous messages',
    'sendMessage': 'Send Message',
    'sendAnonymously': 'Send message anonymously',
    'searchStudent': 'Search Student',
    'receiver': 'Receiver',
    'noStudents': 'No students',
    'selected': ' selected',
    'type': 'Type',
    'selectType': 'Select type',
    'projectProposal': 'Project Proposal',
    'mentorMentee': 'Mentor/Mentee',
    'schoolContest': 'School Contest',
    'club': 'Club',
    'otherQuestion': 'Other Question',
    'content': 'Content',
    'enterMessageContent': 'Enter message content...',
    'send': 'Send',
    'sentMessages': 'Sent Messages',
    'receivedMessages': 'Received Messages',
    'onHold': 'On Hold',
    'chatRooms': 'Chat Rooms',
    'to': 'To',
    'from': 'From',
    'anonymous': 'Anonymous',
    'accepted': 'Accepted',
    'rejected': 'Rejected',
    'pending': 'Pending',
    'accept': 'Accept',
    'reject': 'Reject',
    'hold': 'Hold',
    'noSentMessages': 'No sent messages',
    'noReceivedMessages': 'No received messages',
    'noPendingMessages': 'No pending messages',
    'chatRoomList': 'Chat Room List',
    'noChatRooms': 'No chat rooms',
    'enterMessage': 'Enter message...',
    'selectChatRoom': 'Select a chat room',
    'fillAllFields': 'Please fill all fields',
    'messageSent': 'Message sent',
    'messageAccepted': 'Message accepted. Chat room created.',
    'confirmReject': 'Are you sure you want to reject this message?',
    'messageRejected': 'Message rejected',
    'messagePending': 'Message put on hold',
    // Directory
    'studentList': 'Student List',
    'checkByGrade': 'Check students by grade',
    'searchByName': 'Search by name...',
    'all': 'All',
    'sendDirectMessage': 'Send Message',
    'totalStudents': 'Total {count} students',
    // Settings
    'manageSettings': 'Manage account settings',
    'interests': 'Interests',
    'addInterests': 'Add topics or activities of interest',
    'addInterestPlaceholder': 'Add interest (e.g: basketball, math)',
    'add': 'Add',
    'addInterestsPrompt': 'Add your interests',
    'changePassword': 'Change Password',
    'setNewPassword': 'Set new password',
    'currentPassword': 'Current Password',
    'newPassword': 'New Password',
    'confirmNewPassword': 'Confirm New Password',
    'dangerZone': 'Danger Zone',
    'deleteAccountWarning': 'Account deletion cannot be undone',
    'deleteAccount': 'Delete Account',
    'confirmDelete': 'Are you sure you want to delete?',
    'deleteDescription': 'This action cannot be undone. All data will be permanently deleted.',
    'cancel': 'Cancel',
    // Home page translations
    'welcomeUser': 'Welcome, {name}',
    'checkLatestPosts': 'Check latest posts from KGSCP student community',
    'noPosts': 'No posts yet',
    'justNow': 'Just now',
    'hoursAgo': '{hours} hours ago',
    'daysAgo': '{days} days ago',
    'loading': 'Loading...',
    // Boards page translations
    'boardTitle': 'Boards',
    'shareStories': 'Share school news and stories',
    'category': 'Category',
    'searchTitle': 'Search title',
    'search': 'Search...',
    'categoryAll': 'All',
    'categoryFree': 'Free Board',
    'categoryClub': 'Club',
    'categoryAssignment': 'School Assignment',
    'categorySubject': 'Subject',
    'categoryContest': 'School Contest',
    'categoryMentor': 'Mentor/Mentee',
    'categoryOther': 'Other',
    'newPost': 'New Post',
    'selectCategory': 'Select category',
    'title': 'Title',
    'enterTitle': 'Enter title',
    'enterContent': 'Enter content',
    'fileUpload': 'File Upload',
    'chooseFile': 'Choose file',
    'postAsAnonymous': 'Post anonymously',
    'submit': 'Submit',
    'backToList': 'Back to list',
    'delete': 'Delete',
    'like': 'Like',
    'dislike': 'Dislike',
    'comment': 'Comment',
    'comments': 'Comments',
    'writeComment': 'Write a comment...',
    'postComment': 'Post Comment',
    'reply': 'Reply',
    'firstComment': 'Be the first to comment',
    'replyingTo': 'Replying...',
    'confirmDeletePost': 'Are you sure you want to delete this post?',
    'confirmDeleteComment': 'Are you sure you want to delete this comment?',
    // Profile page translations
    'profileUpdated': 'Profile updated',
    'manageProfile': 'Manage your profile information',
    'edit': 'Edit',
    'editProfile': 'Edit Profile',
    'basicInfo': 'Basic Information',
    'class': 'Class',
    'classNumber': 'Class Number',
    'classPlaceholder': 'e.g: Class 1',
    'academicInfo': 'Academic Information',
    'mbtiPlaceholder': 'e.g: ENFP',
    'toeflPlaceholder': 'e.g: 110',
    'satPlaceholder': 'e.g: 1450',
    'apPlaceholder': 'e.g: Calculus BC (5)',
    'otherScores': 'Other Scores',
    'otherScoresPlaceholder': 'e.g: IELTS 8.0',
    'gpa': 'GPA',
    'gpaPlaceholder': 'e.g: 4.0',
    'bestSubject': 'Best Subject',
    'bestSubjectPlaceholder': 'e.g: Math',
    'bio': 'Bio',
    'bioPlaceholder': 'Introduce yourself...',
    'save': 'Save',
    'characterLimit': '{current}/{max}',
    'mbti': 'MBTI',
    'toefl': 'TOEFL',
    'sat': 'SAT',
    'ap': 'AP',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ko')

  useEffect(() => {
    const saved = localStorage.getItem('kgscp_language') as Language
    if (saved && ['ko', 'vi', 'en'].includes(saved)) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('kgscp_language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ko] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
